#!/bin/sh
# SPIRE Agent entrypoint — reads the join token from env var and starts the agent.
#
# Why a separate entrypoint?
# The join token is a one-time credential generated by the SPIRE server AFTER it starts.
# We can't hardcode it in agent.conf because it's dynamic.
# The demo script (07_spire_demo.py) generates the token and passes it via SPIRE_JOIN_TOKEN.
set -e

if [ -z "$SPIRE_JOIN_TOKEN" ] || [ "$SPIRE_JOIN_TOKEN" = "placeholder-set-by-07_spire_demo.py" ]; then
    echo "ERROR: SPIRE_JOIN_TOKEN is not set or is still the placeholder."
    echo "       The demo script 07_spire_demo.py should set this before starting the agent."
    exit 1
fi

echo "[agent-entrypoint] Starting SPIRE agent with join token: ${SPIRE_JOIN_TOKEN:0:8}..."
exec /opt/spire/bin/spire-agent run \
    -config /opt/spire/conf/agent/agent.conf \
    -joinToken "${SPIRE_JOIN_TOKEN}"
